### ISSUE TITLE
building the executable

### ISSUE THREAD

**Issue by Marco-Israel** [yduf/yduf.github.io#2]
Hello,

is it pussible that testmate can build the test executable by e.g trigger the correspondig makefile?  

I like to edit a test and when pressing the "run" or "debug" button/link above the test, testmate should recompile the executable before  executing the test. Same for debug.

Currently i need to rebuild the executable by cmake or make first. if not the changes I made to the test are not avialable to the test-executable because it is not rebuilded.

Is there a solution or does I have only a misconfigured cmake projekt?

**Comment by yduf** [comment]
closing as duplicate
